runtime: ruby21

env:
  HTTP_PORT: "${HTTP_PORT:-8080}"
  ROCK_ENV: development

run: exec shotgun --server=thin --port=$HTTP_PORT config.ru

run_web: exec unicorn -c config/unicorn.rb -E "${ROCK_ENV}"
